apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: n8n

data:
  GENERIC_TIMEZONE: "America/Sao_Paulo"
  N8N_PORT: "5678"
  N8N_PROTOCOL: "https"
  N8N_HOST: "n8n.seudominio.com"
  WEBHOOK_URL: "https://n8n.seudominio.com"