apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: n8n
type: Opaque

stringData:
  postgres-user: n8n
  postgres-password: MboZ/Q28PeVDmQ
  postgres-db: n8n

  n8n-encryption-key: AyYKp9qBEMI4XC2WtiWxWc1F+YFvsEnIDksQ7/wuiwQ

  tailscale-auth-key: tskey-xxxxx